name: "Dakota's Portfolio"
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e6e6e'
    - '#393939'
    - '#ff5a0a'
    - '#fe9901'
    - '#f3843d'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3797797132283449
  rhythmicContrast: 0.5
purpose: []
